### ISSUE TITLE
q

### ISSUE THREAD

**Issue by GGnoWP** [aetrnyx/discord-activities#10]
Hello,how do I remove this from the code and leave only a hyperlink ?
![image](https://user-images.githubusercontent.com/83351891/190891662-7457d62f-4bc1-49fb-aa2e-3ffa8e505ba4.png)

**Comment by a3ryk** [comment]
![image](https://user-images.githubusercontent.com/53209134/193255215-f6975a3d-33d3-4cbd-ad13-2d056a850af7.png)

If you meant removing the embed like above then put the link inside `<LINK>`
Eg. `<https://discord.com/invite/sQS4QZ2c>`
